name: Tests

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nim: ['stable', 'devel']
    name: Nim ${{ matrix.nim }} test
    steps:
    - name: Setup Nim Enviroment
      uses: actions/checkout@v3

    - uses: jiro4989/setup-nim-action@v2
      with:
          use-nightlies: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          nim-version: ${{ matrix.nim }}

    - name: Run Tests
      run: nimble test
      
    - name: Test doc examples
      run: nimble doc --warningAsError:BrokenLink:on --project src/fogair.nim

  
  deploy:
    needs: test
    permissions:
      pages: write # To deploy to Pages
      id-token: write # Verify deployment
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4

      - name: "Setup nim"
        uses: jiro4989/setup-nim-action@v2

      - name: "Build documentation"
        uses: ire4ever1190/nim-docs-action@v1
        with:
          main-file: "src/fogair.nim"
          deploy: "pages"
